---
- name: Keepalived
  hosts: all
  become: true
  become_method: sudo
  vars:
    vip: "{{ hostvars['vrrp']['ansible_host'] }}"
    master_ip: "{{ hostvars['master']['ansible_host'] }}"
    backup_ip: "{{ hostvars['backup']['ansible_host'] }}"
    interface: "{{ ansible_default_ipv4.interface }}"
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        state: present
        update_cache: true
        pkg:
          - keepalived
          - net-tools

    - name: Enable IP forwarding
      ansible.builtin.copy:
        src: keepalived.conf
        dest: /etc/sysctl.d/keepalived.conf
        mode: 0644

    - name: Create keepalived.conf for master
      ansible.builtin.template:
        src: master.conf
        dest: /etc/keepalived/keepalived.conf
        mode: 0644
        backup: true
      when: inventory_hostname == 'master'

    - name: Create keepalived.conf for backup
      ansible.builtin.template:
        src: backup.conf
        dest: /etc/keepalived/keepalived.conf
        mode: 0644
        backup: true
      when: inventory_hostname == 'backup'

    - name: Reload sysctl
      ansible.builtin.command: sysctl --system

    - name: Restart keepalived
      ansible.builtin.service:
        name: keepalived
        state: restarted
        enabled: true
